apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg-admin-admin-service-fe-qa
  namespace: admin-service
  labels:
    app.kubernetes.io/instance: lg-admin-admin-service-fe-qa
    app.kubernetes.io/name: lg-admin-admin-service-fe-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: lg-admin-admin-service-fe-qa
      app.kubernetes.io/name: lg-admin-admin-service-fe-qa
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: lg-admin-admin-service-fe-qa
        app.kubernetes.io/name: lg-admin-admin-service-fe-qa
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - lg-admin-admin-service-fe-qa
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: lg-admin-admin-service-fe-qa
          image: IMAGE_VERSION
          ports:
          - containerPort: 80
#      nodeSelector:
#        subnets_good: private1_private2
