apiVersion: v1
kind: Service
metadata:
  name: lg-admin-admin-service-fe-qa
  labels:
    app.kubernetes.io/instance: lg-admin-admin-service-fe-qa
    app.kubernetes.io/name: lg-admin-admin-service-fe-qa
  annotations:
  namespace: admin-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: lg-admin-admin-service-fe-qa
    app.kubernetes.io/name: lg-admin-admin-service-fe-qa