apiVersion: v1
kind: Secret
metadata:
  name: ai-services-secret-stg
  namespace: ai-service
type: Opaque
stringData:
  ### Product Comparison Variables ###
  PDS_DB_HOST: "ENV_PDS_DB_HOST"
  PDS_DB_PORT: "ENV_PDS_DB_PORT"
  PDS_DB_USER: "ENV_PDS_DB_USER"
  PDS_DB_PASSWORD: "ENV_PDS_DB_PASSWORD"
  PDS_DB_NAME: "ENV_PDS_DB_NAME"
  AI_DB_HOST: "ENV_AI_DB_HOST"
  AI_DB_PORT: "ENV_AI_DB_PORT"
  AI_DB_USER: "ENV_AI_DB_USER"
  AI_DB_PASSWORD: "ENV_AI_DB_PASSWORD"
  AI_DB_NAME: "ENV_AI_DB_NAME"
  REDIS_HOST: "ENV_REDIS_HOST"
  REDIS_PORT: "ENV_REDIS_PORT"
  REDIS_DB: "ENV_REDIS_DB"
  LITELLM_BASE_URL: "ENV_LITELLM_BASE_URL"
  LITELLM_API_KEY: "ENV_LITELLM_API_KEY"
  LLM_MODEL: "ENV_LLM_MODEL"
  #GUARDRAILS_API_KEY: "ENV_GUARDRAILS_API_KEY"
  SEC_AIC_DB_HOST: "ENV_SEC_AIC_DB_HOST"
  SEC_AIC_DB_PORT: "ENV_SEC_AIC_DB_PORT"
  SEC_AIC_DB_USER: "ENV_SEC_AIC_DB_USER"
  SEC_AIC_DB_PASSWORD: "ENV_SEC_AIC_DB_PASSWORD"
  SEC_AIC_DB_NAME: "ENV_SEC_AIC_DB_NAME"
