apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.appDetail.name }}
  namespace: {{ .Values.common.appDetail.nameSpace }}
type: Opaque
data:
  JAVA_OPTS: {{ "ENV_JAVA_OPTS" | b64enc }}
  NEW_RELIC_APP_NAME: {{ "[ENV_SPRING_PROFILES_ACTIVE] admin-service-be" | b64enc }}
  NEW_RELIC_AGENT_ENABLED: {{ "true" | b64enc }}
  NEW_RELIC_LICENSE_KEY: {{ "ENV_NEW_RELIC_LICENSE_KEY" | b64enc }}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: {{ "ENV_NEW_RELIC_DISTRIBUTED_TRACING_ENABLED" | b64enc }}
  NEW_RELIC_TRANSACTION_EVENTS_MAX_SAMPLES_STORED: {{ "ENV_NEW_RELIC_TRANSACTION_EVENTS_MAX_SAMPLES_STORED" | b64enc }}