apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-services-prd
  namespace: ai-service
spec:
  maxReplicas: MAX_REPLICAS
  minReplicas: MIN_REPLICAS
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ai-services-prd
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 5
