model_list:
  - model_name: openai/us.anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: openai/us.anthropic.claude-3-5-haiku-20241022-v1:0
      api_base: "${LITELLM_BASE_URL}"
      api_key: "${LITELLM_API_KEY}"

general_settings:
  drop_params: true

litellm_settings:
  telemetry: false
