apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.appDetail.name }}
  {{- if or (eq .Values.common.appDetail.branch "develop") (eq .Values.common.appDetail.branch "release") }}
  namespace: {{ .Values.common.appDetail.nameSpace }}
  {{- else }}
  namespace: {{ .Values.common.appDetail.nameSpaceEnv }}
  {{- end }}
type: Opaque
data:
  JAVA_OPTS: {{ "ENV_JAVA_OPTS" | b64enc }}
  NUM_PATH: {{ "ENV_BRANCH_NUM" | b64enc }}